[build-system]
requires = ["maturin>=1.8.6"]
build-backend = "maturin"

[project]
name = "care_survival"
requires-python = ">=3.7"
version = "0.1.0"

[tool.maturin]
features = ["pyo3/extension-module"]
