[project]
name = "care-survival"
version = "0.1.0"
description = "Upgrading survival models with CARE"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["numpy", "pandas"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
