#!/bin/bash
#SBATCH -J score2_care
#SBATCH -A SAMWORTH-SL3-CPU
#SBATCH -p icelake
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6
#SBATCH --mail-type=ALL
#SBATCH --time=03:00:00
#SBATCH --array=201-400

#! Set up modules and environment
. /etc/profile.d/modules.sh
module purge
module load parallel
module load ceuadmin/uv
export I_MPI_PIN_DOMAIN=omp:compact
export I_MPI_PIN_ORDER=scatter
export OMP_NUM_THREADS=4
export MKL_NUM_THREADS=4
export OPENBLAS_NUM_THREADS=4
cd $SLURM_SUBMIT_DIR
echo "Started: $(date)"

#! Unpack job array
MODEL=$(( ($SLURM_ARRAY_TASK_ID - 1) / 40 + 1 ))
SEX_ID=$(( (($SLURM_ARRAY_TASK_ID - 1) % 40) / 20 ))
if (( SEX_ID == 0 )); then
    SEX="female"
else
    SEX="male"
fi
REP=$(( ($SLURM_ARRAY_TASK_ID - 1) % 20 + 1 ))

#! Run jobs
#! if [[ "$SLURM_ARRAY_TASK_ID" == 1 ]]; then
    #! parallel --lb ./target/release/illustration_score2 {1} ::: female male
#! fi

echo "Array ID: $SLURM_ARRAY_TASK_ID"
uv run ./bin/analysis_score2.py $MODEL $SEX $REP

echo "Finished: $(date)"
