#!/bin/bash
#SBATCH -J score2_care
#SBATCH -A SAMWORTH-SL3-CPU
#SBATCH -p icelake
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mail-type=ALL
#SBATCH --time=01:00:00
#SBATCH --array=1-20

#! Set up modules and environment
. /etc/profile.d/modules.sh
module purge
module load parallel
module load ceuadmin/uv
export I_MPI_PIN_DOMAIN=omp:compact
export I_MPI_PIN_ORDER=scatter
export OMP_NUM_THREADS=4
export MKL_NUM_THREADS=4
export OPENBLAS_NUM_THREADS=4
cd $SLURM_SUBMIT_DIR
echo "Started: $(date)"

#! Run commands
#! if [[ "$SLURM_ARRAY_TASK_ID" == 1 ]]; then
    #! parallel --lb ./target/release/illustration_score2 {1} ::: female male
#! fi

echo "Array ID: $SLURM_ARRAY_TASK_ID"
parallel -j 4 --lb uv run ./bin/analysis_score2.py {1} {2} {3} ::: 1 2 ::: female male ::: $SLURM_ARRAY_TASK_ID

echo "Finished: $(date)"
